### ISSUE TITLE
Complete kubejs ecosystem

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create.run#146]
It will 
replace
- [x] crafttweaker
- [x] jeitweaker
- [x] create Tweaker

Potentially replace
- [ ] #165
- [ ] custom ore gen
- [x] jei integration
- [ ] Interactio
- [ ] mod name tooltip

**Comment by PandaBoy444** [comment]
1 mod replaces 8 mods. Sounds good to me

**Comment by PandaBoy444** [comment]
![Discord_nfLkWprESk](https://user-images.githubusercontent.com/8178413/136265833-db740531-cb9a-4d53-b4b9-0a2cf594555a.png)
