### ISSUE TITLE
Learn from Creativia

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create.run#154]
A new modpack just came out called Creativia (if they had a github page I would link here) 
https://www.curseforge.com/minecraft/modpacks/creativia

It has some interesting concepts that we might be able to learn from, notes on the subject will be under this issue

**Comment by PandaBoy444** [comment]
They had some interesting ideas but our pack ideals are so different that we didn't find anything that could be adapted for us
